org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.daemon=true
org.gradle.daemon.idletimeout=60000
kotlin.incremental=false
kotlin.incremental.multiplatform=false
android.useAndroidX=true
